version: '3.8'

services:
  database:
    container_name: postgres_db
    image: postgres:14
    restart: always
    volumes:
      - statistics_postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    env_file:
      - .env.prod
  
  api:
    container_name: statistics_api
    build: ./
    restart: always
    ports:
      - '8000:8000'
    env_file:
      - .env.prod
    depends_on:
      - database


volumes:
  statistics_postgres_data: