# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scheduler.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fscheduler.proto\"3\n\x0e\x41\x64\x64TaskRequest\x12\x10\n\x08task_obj\x18\x01 \x01(\x0c\x12\x0f\n\x07timeout\x18\x02 \x01(\x05\"\x0e\n\x0cResponseStub\" \n\rTaskIdRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\"!\n\x0eRemoveResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32q\n\x0fSchedulerWorker\x12,\n\x08\x61\x64\x64_task\x12\x0f.AddTaskRequest\x1a\r.ResponseStub\"\x00\x12\x30\n\x0bremove_task\x12\x0e.TaskIdRequest\x1a\x0f.RemoveResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'scheduler_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ADDTASKREQUEST._serialized_start=19
  _ADDTASKREQUEST._serialized_end=70
  _RESPONSESTUB._serialized_start=72
  _RESPONSESTUB._serialized_end=86
  _TASKIDREQUEST._serialized_start=88
  _TASKIDREQUEST._serialized_end=120
  _REMOVERESPONSE._serialized_start=122
  _REMOVERESPONSE._serialized_end=155
  _SCHEDULERWORKER._serialized_start=157
  _SCHEDULERWORKER._serialized_end=270
# @@protoc_insertion_point(module_scope)
