# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import scheduler_pb2 as scheduler__pb2


class SchedulerWorkerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.add_task = channel.unary_unary(
                '/SchedulerWorker/add_task',
                request_serializer=scheduler__pb2.AddTaskRequest.SerializeToString,
                response_deserializer=scheduler__pb2.ResponseStub.FromString,
                )
        self.remove_task = channel.unary_unary(
                '/SchedulerWorker/remove_task',
                request_serializer=scheduler__pb2.TaskIdRequest.SerializeToString,
                response_deserializer=scheduler__pb2.RemoveResponse.FromString,
                )


class SchedulerWorkerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def add_task(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def remove_task(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SchedulerWorkerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'add_task': grpc.unary_unary_rpc_method_handler(
                    servicer.add_task,
                    request_deserializer=scheduler__pb2.AddTaskRequest.FromString,
                    response_serializer=scheduler__pb2.ResponseStub.SerializeToString,
            ),
            'remove_task': grpc.unary_unary_rpc_method_handler(
                    servicer.remove_task,
                    request_deserializer=scheduler__pb2.TaskIdRequest.FromString,
                    response_serializer=scheduler__pb2.RemoveResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SchedulerWorker', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SchedulerWorker(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def add_task(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SchedulerWorker/add_task',
            scheduler__pb2.AddTaskRequest.SerializeToString,
            scheduler__pb2.ResponseStub.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def remove_task(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SchedulerWorker/remove_task',
            scheduler__pb2.TaskIdRequest.SerializeToString,
            scheduler__pb2.RemoveResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
