"""initial

Revision ID: c2c2030766c9
Revises: 
Create Date: 2022-09-22 23:38:02.958980

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c2c2030766c9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statistic',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('search_phrase', sa.String(), nullable=False),
    sa.Column('records_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_statistic_search_phrase'), 'statistic', ['search_phrase'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_statistic_search_phrase'), table_name='statistic')
    op.drop_table('statistic')
    # ### end Alembic commands ###
